<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Workflow to Develop and Validate a Prediction model in Multiply Imputed data • psfmi</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Workflow to Develop and Validate a Prediction model in Multiply Imputed data">
<meta property="og:description" content="psfmi">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">psfmi</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.7.1</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/MI_boot.html">Multiple Imputation and Bootstrapping - Method MI_boot</a>
    </li>
    <li>
      <a href="../articles/MI_cv_naive.html">Multiple Imputation and Cross-validation - The MI_cv_naive method</a>
    </li>
    <li>
      <a href="../articles/boot_MI.html">Multiple Imputation and Bootstrapping - Method boot_MI</a>
    </li>
    <li>
      <a href="../articles/cv_MI.html">Multiple Imputation and Cross-validation - method cv_MI</a>
    </li>
    <li>
      <a href="../articles/cv_MI_RR.html">Multiple Imputation and Cross-validation - Method cv_MI_RR</a>
    </li>
    <li>
      <a href="../articles/development_workflow.html">Workflow to Develop and Validate a Prediction model in Multiply Imputed data</a>
    </li>
    <li>
      <a href="../articles/psfmi_CoxModels.html">Pooling and Selection of Cox Regression Models</a>
    </li>
    <li>
      <a href="../articles/psfmi_LogisticModels.html">Pooling and Selection of Logistic Regression Models</a>
    </li>
    <li>
      <a href="../articles/psfmi_StabilityAnalysis.html">Stability analysis after Multiple Imputation</a>
    </li>
    <li>
      <a href="../articles/psfmi_mice.html">Working together: mice and psfmi</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/mwheymans/psfmi/">
    <span class="fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="development_workflow_files/accessible-code-block-0.0.1/empty-anchor.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Workflow to Develop and Validate a Prediction model in Multiply Imputed data</h1>
                        <h4 class="author">Martijn W Heymans</h4>
            
            <h4 class="date">2021-01-12</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/mwheymans/psfmi/blob/master/vignettes/development_workflow.Rmd"><code>vignettes/development_workflow.Rmd</code></a></small>
      <div class="hidden name"><code>development_workflow.Rmd</code></div>

    </div>

    
    
<div id="introduction" class="section level1 unnumbered">
<h1 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h1>
<p>This vignette shows how to develop, internally and externally validate a (logistic) regression prediction model with <code>mice</code> and <code>psfmi</code>.</p>
</div>
<div id="steps" class="section level1 unnumbered">
<h1 class="hasAnchor">
<a href="#steps" class="anchor"></a>Steps</h1>
<ul>
<li><a href="#step-1---install-the-psfmi-and-mice-package">Step 1 - Install the psfmi and mice package</a></li>
<li><a href="#step-2---impute-the-missing-data-with-mice">Step 2 - Impute the missing data with mice</a></li>
<li><a href="#step-3---develop-the-model">Step 3 - Develop the model</a></li>
<li><a href="#step-4---determine-model-performance">Step 4 - Determine model performance</a></li>
<li><a href="#step-5---internally-validate-the-model">Step 5 - Internally validate the model</a></li>
<li><a href="#step-6---shrink-pooled-coefficients-and-determine-new-intercept">Step 6 - Shrink pooled coefficients and determine new intercept</a></li>
<li><a href="#step-7---externally-validate-the-model">Step 7 - Externally validate the model</a></li>
</ul>
<div id="step-1---install-the-psfmi-and-mice-package" class="section level2 unnumbered">
<h2 class="hasAnchor">
<a href="#step-1---install-the-psfmi-and-mice-package" class="anchor"></a>Step 1 - Install the psfmi and mice package</h2>
<p>You can install the released version of psfmi with:</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"psfmi"</span><span class="op">)</span></code></pre></div>
<p>And the development version from <a href="https://github.com/">GitHub</a> with:</p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># install.packages("devtools")</span>
<span class="fu">devtools</span><span class="fu">::</span><span class="fu">install_github</span><span class="op">(</span><span class="st">"mwheymans/psfmi"</span><span class="op">)</span></code></pre></div>
<p>You can install the released version of mice with:</p>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"mice"</span><span class="op">)</span></code></pre></div>
<p>Back to <a href="#steps">Steps</a></p>
</div>
<div id="step-2---impute-the-missing-data-with-mice" class="section level2 unnumbered">
<h2 class="hasAnchor">
<a href="#step-2---impute-the-missing-data-with-mice" class="anchor"></a>Step 2 - Impute the missing data with mice</h2>
<p>I generated 5 imputed datasets to handle the missing values in the lbp_orig dataset that is included in the <code>psfmi</code> package. Depending on the amount of missing data, the number of imputed datasets may be increased (see on-line book: <a href="https://bookdown.org/mwheymans/bookmi/multiple-imputation.html#number-of-imputed-datasets-and-iterations">Applied Missing Data analysis</a>).</p>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R">  <span class="va">imp</span> <span class="op">&lt;-</span> <span class="fu">mice</span><span class="op">(</span><span class="va">lbp_orig</span>, m<span class="op">=</span><span class="fl">5</span>, maxit<span class="op">=</span><span class="fl">10</span>, seed <span class="op">=</span> <span class="fl">750</span><span class="op">)</span> </code></pre></div>
<pre><code>## 
##  iter imp variable
##   1   1  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   1   2  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   1   3  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   1   4  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   1   5  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   2   1  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   2   2  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   2   3  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   2   4  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   2   5  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   3   1  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   3   2  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   3   3  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   3   4  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   3   5  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   4   1  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   4   2  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   4   3  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   4   4  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   4   5  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   5   1  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   5   2  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   5   3  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   5   4  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   5   5  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   6   1  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   6   2  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   6   3  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   6   4  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   6   5  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   7   1  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   7   2  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   7   3  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   7   4  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   7   5  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   8   1  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   8   2  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   8   3  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   8   4  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   8   5  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   9   1  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   9   2  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   9   3  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   9   4  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   9   5  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   10   1  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   10   2  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   10   3  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   10   4  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport
##   10   5  Carrying  Pain  Tampascale  Function  Radiation  Age  Satisfaction  JobControl  JobDemands  SocialSupport</code></pre>
<p>Use the <code>complete</code> function of the <code>mice</code> package to extract the completed datasets. By setting <code>action = "long"</code> and <code>include = FALSE</code>, the imputed datasets are stacked under each other to form one long dataset and the original dataset (that included missing values) is not included in that long dataset.</p>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R">  <span class="va">data_comp</span> <span class="op">&lt;-</span> <span class="fu">complete</span><span class="op">(</span><span class="va">imp</span>, action <span class="op">=</span> <span class="st">"long"</span>, include <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<p>Back to <a href="#steps">Steps</a></p>
</div>
<div id="step-3---develop-the-model" class="section level2 unnumbered">
<h2 class="hasAnchor">
<a href="#step-3---develop-the-model" class="anchor"></a>Step 3 - Develop the model</h2>
<p>Use the <code>psfmi_lr</code> function in the <code>psfmi</code> package to perform backward selection over the 5 multiply imputed datasets with a p-value of 0.05 and as selection method D1.<br><strong>Note</strong> that with this function it is possible to include cubic spline coefficients in case of non-linear relationships during backward selection and that predictors may be forced in the model during backward selection by including them at the setting <code>keep.predictors</code>. When the setting <code>direction</code> is changed to FW, forward selection is done.</p>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R">  <span class="va">pool_lr</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/psfmi_lr.html">psfmi_lr</a></span><span class="op">(</span>data<span class="op">=</span><span class="va">data_comp</span>, nimp<span class="op">=</span><span class="fl">5</span>, impvar<span class="op">=</span><span class="st">".imp"</span>, Outcome<span class="op">=</span><span class="st">"Chronic"</span>,
  predictors<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Gender"</span>, <span class="st">"Age"</span>, <span class="st">"JobControl"</span>, <span class="st">"Tampascale"</span>, <span class="st">"Pain"</span>, <span class="st">"Radiation"</span>,
  <span class="st">"JobDemands"</span>, <span class="st">"SocialSupport"</span>, <span class="st">"Smoking"</span><span class="op">)</span>, cat.predictors <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Satisfaction"</span>, <span class="st">"Carrying"</span><span class="op">)</span>, 
  spline.predictors <span class="op">=</span> <span class="st">"Function"</span>, nknots <span class="op">=</span> <span class="fl">3</span>,  
  keep.predictors <span class="op">=</span> <span class="st">"Radiation"</span>, p.crit <span class="op">=</span> <span class="fl">0.157</span>, method<span class="op">=</span><span class="st">"D1"</span>, direction <span class="op">=</span> <span class="st">"BW"</span><span class="op">)</span></code></pre></div>
<pre><code>## Removed at Step 1 is - Gender</code></pre>
<pre><code>## Removed at Step 2 is - JobDemands</code></pre>
<pre><code>## Removed at Step 3 is - Smoking</code></pre>
<pre><code>## Removed at Step 4 is - Age</code></pre>
<pre><code>## Removed at Step 5 is - Tampascale</code></pre>
<pre><code>## Removed at Step 6 is - rcs(Function,3)</code></pre>
<pre><code>## Removed at Step 7 is - JobControl</code></pre>
<pre><code>## Removed at Step 8 is - SocialSupport</code></pre>
<pre><code>## 
## Selection correctly terminated, 
## No more variables removed from the model</code></pre>
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R">  <span class="va">pool_lr</span><span class="op">$</span><span class="va">RR_model_final</span></code></pre></div>
<pre><code>## $`Step 9`
##                    term   estimate std.error  statistic        df      p.value
## 1           (Intercept) -5.6290593 1.1754061 -4.7890336  39.95530 2.318419e-05
## 2                  Pain  0.9354091 0.1851492  5.0521901  67.68397 3.532584e-06
## 3             Radiation  0.5186631 0.5151459  1.0068276  91.48901 3.166731e-01
## 4 factor(Satisfaction)2 -0.4282950 0.6531511 -0.6557364  44.49919 5.153699e-01
## 5 factor(Satisfaction)3 -2.6431297 0.9429219 -2.8031270  26.83928 9.283867e-03
## 6     factor(Carrying)2  1.2554087 0.6254666  2.0071556  78.40085 4.817958e-02
## 7     factor(Carrying)3  1.6871723 0.6473849  2.6061349 115.47451 1.036350e-02
##            OR    lower.EXP  upper.EXP
## 1 0.003591953 0.0003338808  0.0386429
## 2 2.548255652 1.7610642412  3.6873197
## 3 1.679780430 0.6037849102  4.6732905
## 4 0.651619185 0.1747816872  2.4293596
## 5 0.071138280 0.0102714430  0.4926917
## 6 3.509272384 1.0103539396 12.1887907
## 7 5.404177760 1.4991278521 19.4814186</code></pre>
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r">
<code class="sourceCode R">  <span class="va">pool_lr</span><span class="op">$</span><span class="va">multiparm_final</span></code></pre></div>
<pre><code>## $`Step 9`
##                       p-values D1 F-statistic
## Pain                 1.275830e-06   25.524625
## Radiation            3.148421e-01    1.013702
## factor(Satisfaction) 2.426042e-02    4.267156
## factor(Carrying)     3.261509e-02    3.483376</code></pre>
<p>The same result can be obtained by using the <code>formula</code> setting in the <code>psfmi_lr</code> function</p>
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r">
<code class="sourceCode R">  <span class="va">pool_lr</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/psfmi_lr.html">psfmi_lr</a></span><span class="op">(</span>data<span class="op">=</span><span class="va">data_comp</span>, nimp<span class="op">=</span><span class="fl">5</span>, impvar<span class="op">=</span><span class="st">".imp"</span>, 
  formula <span class="op">=</span> <span class="va">Chronic</span> <span class="op">~</span> <span class="va">Gender</span> <span class="op">+</span> <span class="va">Age</span> <span class="op">+</span> <span class="va">JobControl</span> <span class="op">+</span> <span class="va">Tampascale</span> <span class="op">+</span> <span class="va">Pain</span> <span class="op">+</span> <span class="va">Radiation</span> <span class="op">+</span>
    <span class="va">JobDemands</span> <span class="op">+</span> <span class="va">SocialSupport</span> <span class="op">+</span> <span class="va">Smoking</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">Satisfaction</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">Carrying</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">rcs</span><span class="op">(</span><span class="va">Function</span>, <span class="fl">3</span><span class="op">)</span>, keep.predictors <span class="op">=</span> <span class="st">"Radiation"</span>, 
  p.crit <span class="op">=</span> <span class="fl">0.157</span>, method<span class="op">=</span><span class="st">"D1"</span>, direction <span class="op">=</span> <span class="st">"BW"</span><span class="op">)</span></code></pre></div>
<pre><code>## Removed at Step 1 is - Gender</code></pre>
<pre><code>## Removed at Step 2 is - JobDemands</code></pre>
<pre><code>## Removed at Step 3 is - Smoking</code></pre>
<pre><code>## Removed at Step 4 is - Age</code></pre>
<pre><code>## Removed at Step 5 is - Tampascale</code></pre>
<pre><code>## Removed at Step 6 is - rcs(Function,3)</code></pre>
<pre><code>## Removed at Step 7 is - JobControl</code></pre>
<pre><code>## Removed at Step 8 is - SocialSupport</code></pre>
<pre><code>## 
## Selection correctly terminated, 
## No more variables removed from the model</code></pre>
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r">
<code class="sourceCode R">  <span class="va">pool_lr</span><span class="op">$</span><span class="va">RR_model_final</span></code></pre></div>
<pre><code>## $`Step 9`
##                    term   estimate std.error  statistic        df      p.value
## 1           (Intercept) -5.6290593 1.1754061 -4.7890336  39.95530 2.318419e-05
## 2                  Pain  0.9354091 0.1851492  5.0521901  67.68397 3.532584e-06
## 3             Radiation  0.5186631 0.5151459  1.0068276  91.48901 3.166731e-01
## 4 factor(Satisfaction)2 -0.4282950 0.6531511 -0.6557364  44.49919 5.153699e-01
## 5 factor(Satisfaction)3 -2.6431297 0.9429219 -2.8031270  26.83928 9.283867e-03
## 6     factor(Carrying)2  1.2554087 0.6254666  2.0071556  78.40085 4.817958e-02
## 7     factor(Carrying)3  1.6871723 0.6473849  2.6061349 115.47451 1.036350e-02
##            OR    lower.EXP  upper.EXP
## 1 0.003591953 0.0003338808  0.0386429
## 2 2.548255652 1.7610642412  3.6873197
## 3 1.679780430 0.6037849102  4.6732905
## 4 0.651619185 0.1747816872  2.4293596
## 5 0.071138280 0.0102714430  0.4926917
## 6 3.509272384 1.0103539396 12.1887907
## 7 5.404177760 1.4991278521 19.4814186</code></pre>
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r">
<code class="sourceCode R">  <span class="va">pool_lr</span><span class="op">$</span><span class="va">multiparm_final</span></code></pre></div>
<pre><code>## $`Step 9`
##                       p-values D1 F-statistic
## Pain                 1.275830e-06   25.524625
## Radiation            3.148421e-01    1.013702
## factor(Satisfaction) 2.426042e-02    4.267156
## factor(Carrying)     3.261509e-02    3.483376</code></pre>
<p>Back to <a href="#steps">Steps</a></p>
</div>
<div id="step-4---determine-model-performance" class="section level2 unnumbered">
<h2 class="hasAnchor">
<a href="#step-4---determine-model-performance" class="anchor"></a>Step 4 - Determine model performance</h2>
<p>The performance of the model selected at step 3 can be determined by using the <code>pool_performance</code> function.</p>
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r">
<code class="sourceCode R">  <span class="va">pool_select</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/psfmi_lr.html">psfmi_lr</a></span><span class="op">(</span>data<span class="op">=</span><span class="va">data_comp</span>, nimp<span class="op">=</span><span class="fl">5</span>, impvar<span class="op">=</span><span class="st">".imp"</span>, 
  formula <span class="op">=</span> <span class="va">Chronic</span> <span class="op">~</span> <span class="va">Pain</span> <span class="op">+</span> <span class="va">Radiation</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">Satisfaction</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">Carrying</span><span class="op">)</span>,  
  p.crit <span class="op">=</span> <span class="fl">1</span>, method<span class="op">=</span><span class="st">"D1"</span><span class="op">)</span>
  
  <span class="va">perf</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/pool_performance.html">pool_performance</a></span><span class="op">(</span>data<span class="op">=</span><span class="va">data_comp</span>, nimp<span class="op">=</span><span class="fl">5</span>, impvar<span class="op">=</span><span class="st">".imp"</span>, 
  Outcome <span class="op">=</span> <span class="st">"Chronic"</span>, predictors <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Pain"</span>, <span class="st">"Radiation"</span>, <span class="st">"factor(Satisfaction)"</span>,
             <span class="st">"factor(Carrying)"</span><span class="op">)</span>, cal.plot<span class="op">=</span><span class="cn">TRUE</span>, plot.indiv<span class="op">=</span><span class="cn">FALSE</span>, groups_cal <span class="op">=</span> <span class="fl">10</span><span class="op">)</span></code></pre></div>
<p><img src="development_workflow_files/figure-html/plot-1.png" width="480"></p>
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r">
<code class="sourceCode R">  <span class="va">perf</span></code></pre></div>
<pre><code>## $ROC_pooled
##             95% Low    AUC 95% Up
## AUC (logit)  0.8144 0.8978 0.9462
## 
## $coef_pooled
##           (Intercept)                  Pain             Radiation 
##            -5.6290593             0.9354091             0.5186631 
## factor(Satisfaction)2 factor(Satisfaction)3     factor(Carrying)2 
##            -0.4282950            -2.6431297             1.2554087 
##     factor(Carrying)3 
##             1.6871723 
## 
## $R2_pooled
## [1] 0.5842591
## 
## $Brier_Scaled_pooled
## [1] 0.4882759
## 
## $nimp
## [1] 5</code></pre>
</div>
<div id="step-5---internally-validate-the-model" class="section level2 unnumbered">
<h2 class="hasAnchor">
<a href="#step-5---internally-validate-the-model" class="anchor"></a>Step 5 - Internally validate the model</h2>
<p>To internally validate the model we use the <code>psfmi_perform</code> function. With this function five different methods can be used to internally validate models in MI data <a href="https://mwheymans.github.io/psfmi/articles/">see these Vignettes</a>, Three methods use cross-validation and two bootstrapping in combination with MI.</p>
<p>We will use cross-validation and more specific the method <a href="https://mwheymans.github.io/psfmi/articles/cv_MI_RR.html">cv_MI_RR</a>. With this method it is possible to integrate backward selection into the cross-validation procedure. The last model that is selected by the psfmi_lr function is internally validated. So, if we want to apply backward selection during cross-validation from the full model we first have to apply the psfmi_lr function without variable selection. That is what we apply here, because we know that variable selection is one of the main reasons that prediction models are over-fitted.</p>
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r">
<code class="sourceCode R">  <span class="va">pool_val</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/psfmi_lr.html">psfmi_lr</a></span><span class="op">(</span>data<span class="op">=</span><span class="va">data_comp</span>, formula <span class="op">=</span> <span class="va">Chronic</span> <span class="op">~</span> <span class="va">Gender</span> <span class="op">+</span> <span class="va">Age</span> <span class="op">+</span> <span class="va">JobControl</span> <span class="op">+</span> <span class="va">Tampascale</span> <span class="op">+</span> 
                      <span class="va">Pain</span> <span class="op">+</span> <span class="va">Radiation</span> <span class="op">+</span> <span class="va">JobDemands</span> <span class="op">+</span> <span class="va">SocialSupport</span> <span class="op">+</span> <span class="va">Smoking</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">Satisfaction</span><span class="op">)</span> <span class="op">+</span> 
                      <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">Carrying</span><span class="op">)</span> <span class="op">+</span> <span class="fu">rcs</span><span class="op">(</span><span class="va">Function</span>, <span class="fl">3</span><span class="op">)</span>, p.crit <span class="op">=</span> <span class="fl">1</span>, direction<span class="op">=</span><span class="st">"BW"</span>,
                      nimp<span class="op">=</span><span class="fl">5</span>, impvar<span class="op">=</span><span class="st">".imp"</span>, method<span class="op">=</span><span class="st">"D1"</span><span class="op">)</span>

  <span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">200</span><span class="op">)</span>
  <span class="va">res_cv</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/psfmi_perform.html">psfmi_perform</a></span><span class="op">(</span><span class="va">pool_val</span>, val_method <span class="op">=</span> <span class="st">"cv_MI_RR"</span>, data_orig <span class="op">=</span> <span class="va">lbp_orig</span>, folds <span class="op">=</span> <span class="fl">5</span>,
                     p.crit<span class="op">=</span><span class="fl">0.05</span>, BW<span class="op">=</span><span class="cn">TRUE</span>, nimp_mice <span class="op">=</span> <span class="fl">10</span>, miceImp <span class="op">=</span> <span class="va">miceImp</span>, printFlag <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## fold 1</code></pre>
<pre><code>## Removed at Step 1 is - Age</code></pre>
<pre><code>## Removed at Step 2 is - Smoking</code></pre>
<pre><code>## Removed at Step 3 is - Gender</code></pre>
<pre><code>## Removed at Step 4 is - Tampascale</code></pre>
<pre><code>## Removed at Step 5 is - JobDemands</code></pre>
<pre><code>## Removed at Step 6 is - rcs(Function,3)</code></pre>
<pre><code>## Removed at Step 7 is - SocialSupport</code></pre>
<pre><code>## Removed at Step 8 is - JobControl</code></pre>
<pre><code>## Removed at Step 9 is - Radiation</code></pre>
<pre><code>## Removed at Step 10 is - factor(Carrying)</code></pre>
<pre><code>## 
## Selection correctly terminated, 
## No more variables removed from the model</code></pre>
<pre><code>## 
## fold 2</code></pre>
<pre><code>## Removed at Step 1 is - rcs(Function,3)</code></pre>
<pre><code>## Removed at Step 2 is - Radiation</code></pre>
<pre><code>## Removed at Step 3 is - Gender</code></pre>
<pre><code>## Removed at Step 4 is - JobControl</code></pre>
<pre><code>## Removed at Step 5 is - Age</code></pre>
<pre><code>## Removed at Step 6 is - SocialSupport</code></pre>
<pre><code>## Removed at Step 7 is - Smoking</code></pre>
<pre><code>## Removed at Step 8 is - JobDemands</code></pre>
<pre><code>## Removed at Step 9 is - Tampascale</code></pre>
<pre><code>## Removed at Step 10 is - factor(Carrying)</code></pre>
<pre><code>## 
## Selection correctly terminated, 
## No more variables removed from the model</code></pre>
<pre><code>## 
## fold 3</code></pre>
<pre><code>## Removed at Step 1 is - Gender</code></pre>
<pre><code>## Removed at Step 2 is - JobDemands</code></pre>
<pre><code>## Removed at Step 3 is - Tampascale</code></pre>
<pre><code>## Removed at Step 4 is - Smoking</code></pre>
<pre><code>## Removed at Step 5 is - JobControl</code></pre>
<pre><code>## Removed at Step 6 is - rcs(Function,3)</code></pre>
<pre><code>## Removed at Step 7 is - Age</code></pre>
<pre><code>## Removed at Step 8 is - SocialSupport</code></pre>
<pre><code>## Removed at Step 9 is - Radiation</code></pre>
<pre><code>## 
## Selection correctly terminated, 
## No more variables removed from the model</code></pre>
<pre><code>## 
## fold 4</code></pre>
<pre><code>## Removed at Step 1 is - Gender</code></pre>
<pre><code>## Removed at Step 2 is - Smoking</code></pre>
<pre><code>## Removed at Step 3 is - JobDemands</code></pre>
<pre><code>## Removed at Step 4 is - JobControl</code></pre>
<pre><code>## Removed at Step 5 is - Radiation</code></pre>
<pre><code>## Removed at Step 6 is - factor(Carrying)</code></pre>
<pre><code>## Removed at Step 7 is - SocialSupport</code></pre>
<pre><code>## Removed at Step 8 is - Age</code></pre>
<pre><code>## 
## Selection correctly terminated, 
## No more variables removed from the model</code></pre>
<pre><code>## 
## fold 5</code></pre>
<pre><code>## Removed at Step 1 is - JobDemands</code></pre>
<pre><code>## Removed at Step 2 is - Gender</code></pre>
<pre><code>## Removed at Step 3 is - Smoking</code></pre>
<pre><code>## Removed at Step 4 is - Tampascale</code></pre>
<pre><code>## Removed at Step 5 is - rcs(Function,3)</code></pre>
<pre><code>## Removed at Step 6 is - Age</code></pre>
<pre><code>## Removed at Step 7 is - Radiation</code></pre>
<pre><code>## Removed at Step 8 is - SocialSupport</code></pre>
<pre><code>## Removed at Step 9 is - JobControl</code></pre>
<pre><code>## Removed at Step 10 is - factor(Carrying)</code></pre>
<pre><code>## 
## Selection correctly terminated, 
## No more variables removed from the model</code></pre>
<div class="sourceCode" id="cb96"><pre class="downlit sourceCode r">
<code class="sourceCode R">  <span class="va">res_cv</span></code></pre></div>
<pre><code>## $stats
##                  Train      Test
## AUC          0.8877807 0.8467882
## Brier scaled 0.4657961 0.3374208
## Rsq          0.5622000 0.5117315
## 
## $slope
##  Intercept      Slope 
## -0.1494438  0.8449148</code></pre>
<p>Back to <a href="#steps">Steps</a></p>
</div>
<div id="step-6---shrink-pooled-coefficients-and-determine-new-intercept" class="section level2 unnumbered">
<h2 class="hasAnchor">
<a href="#step-6---shrink-pooled-coefficients-and-determine-new-intercept" class="anchor"></a>Step 6 - Shrink pooled coefficients and determine new intercept</h2>
<p>We can use the slope value of 0.8449148 that was estimated at the previous step as a shrinkage factor to prevent our model from being overfitted in new data. We do this by multiplying the pooled coefficients with the shrinkage factor and also to determine a new intercept value that is aligned with the shrunken coefficients.</p>
<p>We use the <code>pool_intadj</code> function for this that will provide the adjusted coefficients and new intercept value.</p>
<div class="sourceCode" id="cb98"><pre class="downlit sourceCode r">
<code class="sourceCode R">  <span class="va">pool_select</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/psfmi_lr.html">psfmi_lr</a></span><span class="op">(</span>data<span class="op">=</span><span class="va">data_comp</span>, nimp<span class="op">=</span><span class="fl">5</span>, impvar<span class="op">=</span><span class="st">".imp"</span>, 
  formula <span class="op">=</span> <span class="va">Chronic</span> <span class="op">~</span> <span class="va">Pain</span> <span class="op">+</span> <span class="va">Radiation</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">Satisfaction</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">Carrying</span><span class="op">)</span>,  
  p.crit <span class="op">=</span> <span class="fl">1</span>, method<span class="op">=</span><span class="st">"D1"</span><span class="op">)</span>

  <span class="va">res</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/pool_intadj.html">pool_intadj</a></span><span class="op">(</span><span class="va">pool_select</span>, shrinkage_factor <span class="op">=</span> <span class="fl">0.8449148</span><span class="op">)</span>

  <span class="va">res</span><span class="op">$</span><span class="va">int_adj</span></code></pre></div>
<pre><code>## [1] -4.795145</code></pre>
<div class="sourceCode" id="cb100"><pre class="downlit sourceCode r">
<code class="sourceCode R">  <span class="va">res</span><span class="op">$</span><span class="va">coef_shrink_pooled</span></code></pre></div>
<pre><code>##                  Pain             Radiation factor(Satisfaction)2 
##             0.7903410             0.4382261            -0.3618728 
## factor(Satisfaction)3     factor(Carrying)2     factor(Carrying)3 
##            -2.2332194             1.0607134             1.4255169</code></pre>
<p>The last step is to externally validate this adjusted model.</p>
<p>Back to <a href="#steps">Steps</a></p>
</div>
<div id="step-7---externally-validate-the-model" class="section level2 unnumbered">
<h2 class="hasAnchor">
<a href="#step-7---externally-validate-the-model" class="anchor"></a>Step 7 - Externally validate the model</h2>
<p>We validate the model in an external dataset that is imputed five times due to missing data.</p>
<div class="sourceCode" id="cb102"><pre class="downlit sourceCode r">
<code class="sourceCode R">  <span class="va">res_extval</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/mivalext_lr.html">mivalext_lr</a></span><span class="op">(</span>data.val <span class="op">=</span> <span class="va">lbpmi_extval</span>, nimp <span class="op">=</span> <span class="fl">5</span>, impvar <span class="op">=</span> <span class="st">"Impnr"</span>,
  Outcome <span class="op">=</span> <span class="st">"Chronic"</span>, predictors <span class="op">=</span> <span class="va">pool_lr</span><span class="op">$</span><span class="va">predictors_final</span>,
  lp.orig <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">res</span><span class="op">$</span><span class="va">int_adj</span>, <span class="va">res</span><span class="op">$</span><span class="va">coef_shrink_pooled</span><span class="op">)</span>,
  cal.plot <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Pooled performance measures over m = 5 imputed external validation datasets correctly estimated</code></pre>
<p><img src="development_workflow_files/figure-html/plot2-1.png" width="480"></p>
<div class="sourceCode" id="cb104"><pre class="downlit sourceCode r">
<code class="sourceCode R">  <span class="va">res_extval</span><span class="op">$</span><span class="va">ROC</span></code></pre></div>
<pre><code>## $`ROC (logit)`
##             95% Low    AUC 95% Up
## AUC (logit)  0.7382 0.8482 0.9172
## 
## $`ROC (median)`
## 1st Qu.  Median 3rd Qu. 
## 0.84803 0.84897 0.85366</code></pre>
<div class="sourceCode" id="cb106"><pre class="downlit sourceCode r">
<code class="sourceCode R">  <span class="va">res_extval</span><span class="op">$</span><span class="va">R2_fixed</span></code></pre></div>
<pre><code>## $`Fisher Z (fixed)`
## [1] 0.45587
## 
## $`Median (fixed)`
## 1st Qu.  Median 3rd Qu. 
## 0.46034 0.46045 0.47505</code></pre>
<div class="sourceCode" id="cb108"><pre class="downlit sourceCode r">
<code class="sourceCode R">  <span class="va">res_extval</span><span class="op">$</span><span class="va">HLtest</span></code></pre></div>
<pre><code>##         D         p        df       df2 
##   0.71479   0.67820   8.00000 149.55620</code></pre>
<div class="sourceCode" id="cb110"><pre class="downlit sourceCode r">
<code class="sourceCode R">  <span class="va">res_extval</span><span class="op">$</span><span class="va">LP_pooled_ext</span></code></pre></div>
<pre><code>## intercept     slope 
##  -0.01812   0.88741</code></pre>
<p>In the external dataset the AUC is 0.8482 and the R-squared 0.45587. The Hosmer and Lemeshow test has a p-value of 0.67820, which means that the fit is satisfactory. This is also confirmed on the calibration plot where the calibration curves in each imputed dataset are near the optimal (dashed) line. The slope (regression coefficients) has a value of 0.88741 and slightly deviates from the value of 1, which means that the coefficients values differ between the development and external dataset.</p>
<p>Back to <a href="#steps">Steps</a></p>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Martijn Heymans.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
